version: 2

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./batect setup
      - run:
          name: Build
          command: ./batect build
      - run:
          name: Check formatting
          command: ./batect checkFormatting
      - run:
          name: Vet
          command: ./batect vet
      - run:
          name: Run unit tests
          command: ./batect unitTest
      - run:
          name: Run journey tests
          command: ./batect journeyTest
      - store_test_results:
          path: test-results
